### ISSUE TITLE
Unnecessary. Already in wikimeower plans

### ISSUE THREAD

**Issue by CloudGate1234** [meower-media-co/meower-history#1]
we don't need anything separate for meower history. that is going to be part of wikimeower. I like the UI though. we should use it for wikimeower and delete this

**Comment by Mwalters75** [comment]
Okay, I'll start the transition now. I'll close this issue when finished, then this repositoory. Thank you!

**Comment by Mwalters75** [comment]
Submitted the issue (request) on WikiMeower: https://github.com/meower-media-co/WikiMeower/issues/5

**Comment by Mwalters75** [comment]
Due to no answers, repository had been transfered to my personal ownership.

**Comment by Mwalters75** [comment]
Page had been published by WikiMeower MediaWiki: [https://meower.miraheze.org/wiki/History](https://meower.miraheze.org/wiki/History)

**Comment by CloudGate1234** [comment]
ok, the I suppose we don't need this anymore. closing now
